cursor #efdfe1
cursor_text_color #d5c2c6

foreground            #efdfe1
background            #191113
selection_foreground  #422931
selection_background  #e2bdc7
active_border_color   #ffb0c9
inactive_border_color #191113
url_color             #ffb0c9

active_tab_foreground   #ffd9e3
active_tab_background   #6f3349
inactive_tab_foreground #d5c2c6
inactive_tab_background #514347
tab_bar_background      #191113

mark1_foreground #191113
mark1_background #ffb0c9
mark2_foreground #191113
mark2_background #e2bdc7

# black
color0 #191113
color8 #514347

# red
color1 #ffb4ab
color9 #93000a

# green
color2 #efbc94
color10 #623f20

# yellow
color3 #e2bdc7
color11 #5a3f47

# blue
color4 #ffb0c9
color12 #6f3349

# magenta
color5 #efbc94
color13 #5a3f47

# cyan
color6 #e2bdc7
color14 #623f20

# white
color7 #efdfe1
color15 #d5c2c6
