cursor #e6e2d5
cursor_text_color #cac7b5

foreground            #e6e2d5
background            #14140c
selection_foreground  #333118
selection_background  #ccc8a4
active_border_color   #cfca74
inactive_border_color #14140c
url_color             #cfca74

active_tab_foreground   #ece68d
active_tab_background   #4c4800
inactive_tab_foreground #cac7b5
inactive_tab_background #49473a
tab_bar_background      #14140c

mark1_foreground #14140c
mark1_background #cfca74
mark2_foreground #14140c
mark2_background #ccc8a4

# black
color0 #14140c
color8 #49473a

# red
color1 #ffb4ab
color9 #93000a

# green
color2 #a5d0ba
color10 #274e3e

# yellow
color3 #ccc8a4
color11 #4a482c

# blue
color4 #cfca74
color12 #4c4800

# magenta
color5 #a5d0ba
color13 #4a482c

# cyan
color6 #ccc8a4
color14 #274e3e

# white
color7 #e6e2d5
color15 #cac7b5
